site_name: CodeStory CLI Documentation
site_url: https://docs.codestory.build/codestorycli/
plugins:
  - search
  - mkdocs-typer2:
      pretty: true
theme:
    name: material
    features:
      - navigation.sections

nav:
  - Introduction: index.md
  - CLI Reference: reference/root.md