site_name: CodeStory CLI Documentation
site_url: https://docs.codestory.build/
plugins:
  - search
  - mkdocs-typer2:
      pretty: true
theme:
    name: material
    features:
      - navigation.sections

nav:
  - Introduction: index.md
  - Usage Guide: usage/index.md
  - Extensibility: extensibility/index.md
  - Architecture: design/index.md
  - Reference:
      - CLI Commands: reference/root.md
      - Providers & Languages: reference/supported.md